version: '2'

services:
  mongo:
    image: mongo:3.4.6
    restart: always
    volumes:
      - "./.data:/data/db:rw"
      - "./shared_with_mongo:/shared:rw"
    ports:
      - "27017:27017"

#  frontend:
#    build:
#      context: ./frontend
#    restart: always
#    volumes:
#      - "./frontend/:/app/"
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - "./backend/:/app/"
#  nginx-combine:
#    image: nginx
#    restart: always
#    volumes:
#      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
#    ports:
#      - 3000:80
